import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Ruby Red Rose Bouquet',
    description: 'A classic bouquet of one dozen long-stemmed ruby red roses. The ultimate romantic gesture.',
    price: 79.99,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'red roses',
    category: 'Flowers',
    occasion: 'Anniversary',
    color: 'Red',
  },
  {
    id: '2',
    name: 'Sunny Day Sunflowers',
    description: 'Brighten anyone\'s day with this cheerful arrangement of vibrant sunflowers.',
    price: 49.99,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'sunflower bouquet',
    category: 'Flowers',
    occasion: 'Congratulations',
    color: 'Yellow',
  },
  {
    id: '3',
    name: 'Elegant Orchid Plant',
    description: 'A graceful Phalaenopsis orchid plant in a ceramic pot. Long-lasting and easy to care for.',
    price: 65.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'white orchid',
    category: 'Plants',
    occasion: 'Thank You',
    color: 'White',
  },
  {
    id: '4',
    name: 'Pastel Dream Arrangement',
    description: 'A dreamy mix of pastel pink and white flowers, including lilies, roses, and carnations.',
    price: 89.99,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'pastel flowers',
    category: 'Flowers',
    occasion: 'Birthday',
    color: 'Pink',
  },
  {
    id: '5',
    name: 'Snake Plant (Sansevieria)',
    description: 'A hardy and stylish snake plant, known for its air-purifying qualities and low maintenance needs.',
    price: 35.50,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'snake plant',
    category: 'Plants',
    occasion: 'Thank You',
    color: 'Green',
  },
  {
    id: '6',
    name: 'Peace Lily Plant',
    description: 'A beautiful Peace Lily in a decorative container, symbolizing peace and sympathy.',
    price: 55.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'peace lily',
    category: 'Plants',
    occasion: 'Sympathy',
    color: 'White',
  },
  {
    id: '7',
    name: 'Autumn Harvest Bouquet',
    description: 'A stunning seasonal bouquet with rich oranges, deep reds, and golden yellows.',
    price: 75.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'autumn flowers',
    category: 'Flowers',
    occasion: 'Seasonal',
    color: 'Orange',
    isSeasonal: true,
  },
  {
    id: '8',
    name: 'Fiddle Leaf Fig Tree',
    description: 'A trendy and impressive Fiddle Leaf Fig tree that makes a statement in any room.',
    price: 150.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'fiddle leaf',
    category: 'Plants',
    occasion: 'Congratulations',
    color: 'Green',
  },
  {
    id: '9',
    name: 'Lavender Fields Bouquet',
    description: 'A calming and fragrant bouquet of fresh lavender and complementary purple blooms.',
    price: 62.99,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'lavender bouquet',
    category: 'Flowers',
    occasion: 'Thank You',
    color: 'Purple',
  },
  {
    id: '10',
    name: 'Mixed Wildflower Bunch',
    description: 'A vibrant and rustic bunch of mixed seasonal wildflowers, perfect for a natural look.',
    price: 58.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'wildflower bouquet',
    category: 'Flowers',
    occasion: 'Birthday',
    color: 'Mixed',
  },
  {
    id: '11',
    name: 'Spring Tulip Medley',
    description: 'A fresh and vibrant medley of colorful tulips, heralding the arrival of spring.',
    price: 54.99,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tulip bouquet',
    category: 'Flowers',
    occasion: 'Seasonal',
    color: 'Mixed',
    isSeasonal: true,
  },
  {
    id: '12',
    name: 'ZZ Plant (Zamioculcas)',
    description: 'An incredibly resilient and low-maintenance ZZ Plant with glossy, dark green leaves.',
    price: 40.00,
    image: 'https://placehold.co/600x400.png',
    aiHint: 'zz plant',
    category: 'Plants',
    occasion: 'Thank You',
    color: 'Green',
  },
];
